spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}

  jwt:
    access:
      expiration: ${JWT_EXPIRATION}
    secret: ${JWT_SECRET_KEY}

kakao:
  rest-key: ${KAKAO_REST_KEY}            # 비즈 API용
  rest-api-key: ${KAKAO_AUTH_API_KEY}    # aud 검증용(이름 하나로 통일 원하면 rest-key만 쓰도록 코드/설정 맞추기)
  oidc:
    issuer: https://kauth.kakao.com
    jwks-uri: https://kauth.kakao.com/.well-known/jwks.json

google:
  client-id: ${GOOGLE_WEB_CLIENT_ID}
  oidc:
    issuer: https://accounts.google.com
    jwks-uri: https://www.googleapis.com/oauth2/v3/certs
  places:
    api-key: ${GOOGLE_PLACES_API_KEY}
    language: ko
    region: KR

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
