spring:
  application:
    name: Dobong
  profiles:
    group:
      local: "local"
      dev: "dev"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  address: 0.0.0.0

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG